[phases.setup]
nixPkgs = ["nodejs_24", "pnpm-9_x"]  # pin to what you know works

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[phases.start]
# Probably use your production start command
cmds = ["npm run start:prod"]
