[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_x"]  # pin to what you know works

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
# Probably use your production start command
cmd = "npm run start:prod"
