# General
pidfile /var/run/redis/redis-server.pid
port 6379
protected-mode no
# tcp-backlog 511

# Logging
# logfile /var/log/redis/redis-server.log
# loglevel notice

# Persistence
# dir /data
# appendonly yes
# appendfilename "appendonly.aof"

# Snapshot (RDB) settings
# save 900 1         # Save the dataset to disk if at least 1 key changes and 900 seconds (15 minutes) have elapsed
# save 300 10        # Save the dataset to disk if at least 10 keys change and 300 seconds (5 minutes) have elapsed
# save 60 10000      # Save the dataset to disk if at least 10,000 keys change and 60 seconds (1 minute) have elapsed