const RedisKeys = {
  // POINTING
  USER_POINTING_SESSIONS: "USER_POINTING_SESSIONS:%(userId)s",
  POINTING_SESSION_DATA: "POINTING_SESSION_DATA:%(sessionId)s",
  POINTING_SESSION_PARTICIPANTS_DATA:
    "POINTING_SESSION_PARTICIPANTS_DATA:%(sessionId)s",

  // RETRO
  USER_RETRO_SESSIONS: "USER_RETRO_SESSIONS:%(userId)s",
  RETRO_SESSION_DATA: "RETRO_SESSION_DATA:%(sessionId)s",
  RETRO_SESSION_PARTICIPANTS_DATA:
    "RETRO_SESSION_PARTICIPANTS_DATA:%(sessionId)s",
};

module.exports = {
  RedisKeys,
};
